default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  database: project_dev
  pool: pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
test:
  adapter: postgresql
  database: project_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: project_prod
  pool: 5
  timeout: 5000
