# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
<<<<<<< HEAD
      secret_key_base:
          462e960bb2039f5511670eb92ec9176093b9de27332c097ecb3ddc43ad4a3ad10ee80ad707568c549b377a183a7b59dafa85e486a40665fd4ae738e217f22ba7
=======
      secret_key_base: 462e960bb2039f5511670eb92ec9176093b9de27332c097ecb3ddc43ad4a3ad10ee80ad707568c549b377a183a7b59dafa85e486a40665fd4ae738e217f22ba7
      # Gooogle keys
>>>>>>> 8cf26a382bf93d62e74ce6a0ba9ad4eb6bfaef25
      GOOGLE_PLACES_KEY:
          AIzaSyAi-zUItf4_COMYhay6XwpuAksIPmhAUmI
      GOOGLE_MAPS_KEY:
          AIzaSyDOw-Z_pipkfE8Sw_AKqKzaggaq01_D5wQ
      GOOGLE_JS_KEY:
          AIzaSyBoKzqakBZHzDCMZhhFUnIPiwz8pWMb6pI
      AWS_ACCESS_KEY_ID:
          AKIAILBXD7VSSXOCBBKA
      AWS_SECRET_ACCESS_KEY:
          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
      S3_REGION:
        us-east-1
      S3_BUCKET:
        dscenebucket1

      #  AWS keys
      S3_REGION:
        us-east-2
      S3_BUCKET:
        veryfirstbucketnycda
      AWS_ACCESS_KEY_ID:
        AKIAIZW5SX3LYKQJXEGQ
      AWS_SECRET_ACCESS_KEY:
        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
test:
  secret_key_base: 5cd5a525888d8acd22442ac63eac71485c615cc3df3cdd6ff6c1ba35f3b262bcba24fb03abed7e0e10f2003dcf500b9d6657ce1da5abbbc79de16edbbd402651

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
    secret_key_base:
        <%= ENV["SECRET_KEY_BASE"] %>
    GOOGLE_PLACES_KEY:
        <%= ENV["GOOGLE_PLACES_KEY"] %>
    GOOGLE_MAPS_KEY:
        <%= ENV["GOOGLE_MAPS_KEY"] %>
    GOOGLE_JS_KEY:
        <%= ENV["GOOGLE_JS_KEY"] %>
    AWS_SECRET_ACCESS_KEY:
        <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    AWS_ACCESS_KEY_ID:
        <%= ENV["AWS_ACCESS_KEY_ID"] %>
    S3_REGION:
        <%= ENV["S3_REGION"] %>
    S3_BUCKET:
        <%= ENV["S3_BUCKET"] %>
